Repository itggot-TE4/Teacher-O-Matic-DJJL, pull requests merged in 2019-10, with the labels that each got.

#2 Feature/1 boilerplate
  .eslintrc.json
  .github/workflows/cc.yml
  .github/workflows/tests.yml
  README.md
  css/style.css
  css/style.css.map
  css/style.scss
  index.html
  js/script.js
  js/script.test.js
  package-lock.json
  package.json
Labels: boilerplate, enhancement

#9 Feature/3 searchbar
  css/style.css
  css/style.css.map
  css/style.scss
  index.html
  js/api.js
  js/script.js
Labels: enhancement

#13 changed method of sizing input in header
  css/style.css
  css/style.css.map
  css/style.scss
Labels: 3p, enhancement

#14 Feature/7 display forks
  js/api.js
  js/script.js
Labels: enhancement

#19 styled search results when searching repos
  .gitignore
  css/style.css
  css/style.css.map
  css/style.scss
  index.html
  js/htmlGen.js
  js/script.js
Labels: enhancement

#22 Feature/18 style forks
  .github/workflows/tests.yml
  css/style.css
  css/style.css.map
  css/style.scss
  index.html
  js/api.js
  js/htmlGen.js
  js/script.js
  package-lock.json
Labels: enhancement

#27 Feature/5 set backend
  .gitignore
  Gemfile
  Gemfile.lock
  config.ru
  public/css/style.css
  public/css/style.css.map
  public/css/style.scss
  public/js/api.js
  public/js/htmlGen.js
  public/js/script.js
  public/js/script.test.js
  server.rb
  views/index.erb
Labels: enhancement

#40 split up forkedFile in two/prepared for automagisk tests
  public/js/api.js
  public/js/event.js
  public/js/htmlGen.js
  views/index.erb
Labels: 3p

#41 Feature/8 automagisk tests
  .gitignore
  public/css/style.css
  public/css/style.css.map
  public/css/style.scss
  public/js/htmlGen.js
  views/index.erb
Labels: enhancement

#43 found them all
  public/js/api.js
  public/js/event.js
  public/js/htmlGen.js
  public/js/script.js
Labels: 1p, 5p, enhancement

#45 replaced the search keydown event with submit
  public/css/style.css
  public/css/style.css.map
  public/css/style.scss
  public/js/event.js
  public/js/script.js
  views/index.erb
Labels: refactor

#54 the main now recieves a message if the main manifest cannot be found
  public/js/api.js
  public/js/event.js
Labels: enhancement

#48 Release 1.0
  .eslintignore
  .eslintrc.js
  .github/workflows/cc.yml
  .github/workflows/tests.yml
  .gitignore
  Gemfile
  Gemfile.lock
  README.md
  config.ru
  docs/API.html
  docs/EventListener.html
  docs/Generator.html
  docs/api.js.html
  docs/event.js.html
  docs/fonts/OpenSans-Bold-webfont.eot
  docs/fonts/OpenSans-Bold-webfont.svg
  docs/fonts/OpenSans-Bold-webfont.woff
  docs/fonts/OpenSans-BoldItalic-webfont.eot
  docs/fonts/OpenSans-BoldItalic-webfont.svg
  docs/fonts/OpenSans-BoldItalic-webfont.woff
  docs/fonts/OpenSans-Italic-webfont.eot
  docs/fonts/OpenSans-Italic-webfont.svg
  docs/fonts/OpenSans-Italic-webfont.woff
  docs/fonts/OpenSans-Light-webfont.eot
  docs/fonts/OpenSans-Light-webfont.svg
  docs/fonts/OpenSans-Light-webfont.woff
  docs/fonts/OpenSans-LightItalic-webfont.eot
  docs/fonts/OpenSans-LightItalic-webfont.svg
  docs/fonts/OpenSans-LightItalic-webfont.woff
  docs/fonts/OpenSans-Regular-webfont.eot
  docs/fonts/OpenSans-Regular-webfont.svg
  docs/fonts/OpenSans-Regular-webfont.woff
  docs/global.html
  docs/htmlGen.js.html
  docs/index.html
  docs/scripts/linenumber.js
  docs/scripts/prettify/Apache-License-2.0.txt
  docs/scripts/prettify/lang-css.js
  docs/scripts/prettify/prettify.js
  docs/styles/jsdoc-default.css
  docs/styles/prettify-jsdoc.css
  docs/styles/prettify-tomorrow.css
  models/comment.rb
  models/database_model.rb
  package-lock.json
  package.json
  public/css/style.css
  public/css/style.css.map
  public/css/style.scss
  public/favicon.ico
  public/js/api.js
  public/js/event.js
  public/js/htmlGen.js
  public/js/script.js
  public/js/script.test.js
  seed.rb
  server.rb
  views/index.erb
Labels: 3p, enhancement
